server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 890902982439-5a65a3mrve015h16viu1i4e6ph7lhcdh.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 892409341928117
            client-secret: f9823f26891b68dfbfe616913ff51e99
            scope:
              - email
              - public_profile
          naver:
            client-id: hYLCwLj9TH4yj5mcvmu9
            client-secret: gKcRQQApit
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.
